name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'run-ci/**'
    tags:
      - 'v*'
  pull_request:

jobs:
  plugin-clang-format:
    name: plugin-clang-format
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install clang-format
        run: |
          apt update
          apt install -y clang-format

      - name: clang-format
        run: |
          bash tests/lint/clang-format/run.sh BlueprintToRSTDoc

  # sample-clang-format:
  #   name: sample-clang-format
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ubuntu:20.04
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Install clang-format
  #       run: |
  #         apt update
  #         apt install -y clang-format

  #     - name: clang-format
  #       run: |
  #         bash tests/lint/clang-format/run.sh samples/SampleProject

  # functional-test-clang-format:
  #   name: functional-test-clang-format
  #   runs-on: ubuntu-latest
  #   container:
  #     image: ubuntu:20.04
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Install clang-format
  #       run: |
  #         apt update
  #         apt install -y clang-format
  #     - name: clang-format
  #       run: |
  #         bash tests/lint/clang-format/run.sh tests/functional_test/FunctionalTest

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm install -g markdownlint-cli

      - name: markdownlint test
        run: bash tests/lint/markdownlint/run.sh .

  yamllint:
    name: yamllint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y python3 python3-pip

      - name: Install required pip packages
        run: pip3 install -r requirements.txt

      - name: yamllint test
        run: bash tests/lint/yamllint/run.sh .

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install required packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shellcheck

      - name: shellcheck test
        run: bash tests/lint/shellcheck/run.sh .

  crlf-check:
    name: crlf-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check CRLF
        uses: erclu/check-crlf@v1
        with:
          path: .
